name: cashier_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  mobile_scanner: ^7.0.0
  open_file: ^3.4.0
  path_provider: ^2.1.1
  permission_handler: ^11.2.0
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  printing: ^5.12.0
  excel: ^2.0.8
  path: ^1.8.2
  http: ^1.1.0
  intl: ^0.19.0
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/

flutter_native_splash:
  image: assets/img/logo_cashier.png
  color: '#FFFFFF'
  android_12:
    image: assets/img/logo_cashier.png
    color: '#FFFFFF'
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/img/app_icon_1024x1024.png
    background_color: '#007211'
    theme_color: '#007211'
  image_path: assets/img/logo_cashier.png
  adaptive_icon_background: '#007211'
  adaptive_icon_foreground: assets/img/logo_cashier.png
  min_sdk_android: 21
